name: formasaurusenv
dependencies:
- numpy=1.10.1=py27_0
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- python=2.7.10=2
- readline=6.2=2
- scikit-learn=0.17=np110py27_1
- scipy=0.16.0=np110py27_1
- setuptools=18.4=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - docopt==0.6.2
  - flask==0.10.1
  - formasaurus==0.2
  - itsdangerous==0.24
  - jinja2==2.8
  - lxml==3.4.4
  - markupsafe==0.23
  - pandas==0.17.0
  - python-dateutil==2.4.2
  - pytz==2015.7
  - six==1.10.0
  - tldextract==1.7.1
  - tqdm==2.2.4
  - werkzeug==0.11

